name: Test and Rebuild

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: -Xmx3200m
      JDK_JAVA_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED
    steps: 
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup submodule
        run: git submodule update --init --recursive
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config build-essential g++ \
            libcairo2-dev libpango1.0-dev libssl-dev \
            libjpeg-dev libgif-dev
          npm set progress=false
          which gulp || npm install -g gulp-cli  
      - name: Install NPM Dependencies
        run: npm ci
      - run: gulp jshint
      - run: gulp minify
      # - run: gulp test
      - run: gulp zip

  rebuild:
    needs: test
    concurrency: ci-${{ github.ref }}  # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install system dependencies for canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            pkg-config build-essential g++ \
            libcairo2-dev libpango1.0-dev libssl-dev \
            libjpeg-dev libgif-dev librsvg2-dev 
      - name: Rebuild
        run: |
          npm install
      - name: Upload built-dist
        uses: actions/upload-artifact@v4
        with:
          name: built-dist
          path: dist
      - name: Upload built-examples
        uses: actions/upload-artifact@v4
        with:
          name: built-examples
          path: examples
      - name: Checkout to develop-builds
        uses: actions/checkout@v3
        with:
          ref: develop-builds
          token: ${{ secrets.T }}
      - name: Clear out things
        run: |
          rm -rf dist/*
          rm -rf examples/*
      - name: Download built-dist
        uses: actions/download-artifact@v4
        with:
          name: built-dist
          path: dist/
      - name: Download built-examples
        uses: actions/download-artifact@v4
        with:
          name: built-examples
          path: examples/
      - name: Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "Build"
          committer_name: GitHub Actions
          committer_email: actions@github.com
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.T }}
          event-type: update
          repository: Dinosaurmod/dinosaurmod.github.io
